package com.archie.codegen.generator;

import com.archie.ai.model.DiagramAnalysisResult;
import com.squareup.javapoet.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.stereotype.Component;

import javax.lang.model.element.Modifier;
import java.util.*;

/**
 * Generates REST controller classes using JavaPoet
 */
@Slf4j
@Component
public class ControllerGenerator {

        /**
         * Generate REST controller for an entity
         */
        public String generateController(DiagramAnalysisResult.EntityMetadata entity, String basePackage) {
                try {
                        log.debug("Generating controller for: {}", entity.getName());

                        String entityClassName = entity.getName();
                        String controllerName = entityClassName + "Controller";
                        String repositoryName = entityClassName + "Repository";
                        String variableName = uncapitalize(entityClassName);

                        // Create type references
                        ClassName entityType = ClassName.get(basePackage + ".entity", entityClassName);
                        ClassName repositoryType = ClassName.get(basePackage + ".repository", repositoryName);
                        ParameterizedTypeName listType = ParameterizedTypeName.get(
                                        ClassName.get(List.class),
                                        entityType);
                        ParameterizedTypeName responseEntityType = ParameterizedTypeName.get(
                                        ClassName.get(ResponseEntity.class),
                                        entityType);

                        // Build controller class
                        TypeSpec.Builder controllerBuilder = TypeSpec.classBuilder(controllerName)
                                        .addModifiers(Modifier.PUBLIC)
                                        .addAnnotation(RestController.class)
                                        .addAnnotation(AnnotationSpec
                                                        .builder(ClassName.get("lombok", "RequiredArgsConstructor"))
                                                        .build())
                                        .addAnnotation(
                                                        AnnotationSpec.builder(RequestMapping.class)
                                                                        .addMember("value", "$S",
                                                                                        "/api/" + variableName + "s")
                                                                        .build())
                                        .addJavadoc("REST API controller for $L operations\n", entityClassName);

                        // Add repository field
                        FieldSpec repositoryField = FieldSpec.builder(repositoryType, "repository")
                                        .addModifiers(Modifier.PRIVATE, Modifier.FINAL)
                                        .build();
                        controllerBuilder.addField(repositoryField);

                        // Add CRUD methods
                        controllerBuilder.addMethod(generateGetAllMethod(entityType, listType, variableName));
                        controllerBuilder
                                        .addMethod(generateGetByIdMethod(entityType, responseEntityType, variableName));
                        controllerBuilder.addMethod(generateCreateMethod(entityType, variableName));
                        controllerBuilder.addMethod(generateUpdateMethod(entityType, responseEntityType, variableName));
                        controllerBuilder.addMethod(generateDeleteMethod(responseEntityType, variableName));

                        // Generate Java file
                        JavaFile javaFile = JavaFile.builder(basePackage + ".controller", controllerBuilder.build())
                                        .addFileComment("Auto-generated by Archie - Blueprint to Boot")
                                        .indent("    ")
                                        .build();

                        return javaFile.toString();

                } catch (Exception e) {
                        log.error("Error generating controller for {}: {}", entity.getName(), e.getMessage(), e);
                        throw new RuntimeException("Failed to generate controller: " + e.getMessage(), e);
                }
        }

        private MethodSpec generateGetAllMethod(ClassName entityType, ParameterizedTypeName listType,
                        String variableName) {
                return MethodSpec.methodBuilder("getAll" + capitalize(variableName) + "s")
                                .addModifiers(Modifier.PUBLIC)
                                .addAnnotation(GetMapping.class)
                                .returns(listType)
                                .addStatement("return repository.findAll()")
                                .build();
        }

        private MethodSpec generateGetByIdMethod(ClassName entityType, ParameterizedTypeName responseEntityType,
                        String variableName) {
                return MethodSpec.methodBuilder("get" + capitalize(variableName) + "ById")
                                .addModifiers(Modifier.PUBLIC)
                                .addAnnotation(
                                                AnnotationSpec.builder(GetMapping.class)
                                                                .addMember("value", "$S", "/{id}")
                                                                .build())
                                .addParameter(
                                                ParameterSpec.builder(Long.class, "id")
                                                                .addAnnotation(PathVariable.class)
                                                                .build())
                                .returns(responseEntityType)
                                .addStatement("return repository.findById(id)\n" +
                                                "    .map($T::ok)\n" +
                                                "    .orElse($T.notFound().build())",
                                                ResponseEntity.class, ResponseEntity.class)
                                .build();
        }

        private MethodSpec generateCreateMethod(ClassName entityType, String variableName) {
                return MethodSpec.methodBuilder("create" + capitalize(variableName))
                                .addModifiers(Modifier.PUBLIC)
                                .addAnnotation(PostMapping.class)
                                .addParameter(
                                                ParameterSpec.builder(entityType, variableName)
                                                                .addAnnotation(RequestBody.class)
                                                                .build())
                                .returns(entityType)
                                .addStatement("return repository.save($L)", variableName)
                                .build();
        }

        private MethodSpec generateUpdateMethod(ClassName entityType, ParameterizedTypeName responseEntityType,
                        String variableName) {
                return MethodSpec.methodBuilder("update" + capitalize(variableName))
                                .addModifiers(Modifier.PUBLIC)
                                .addAnnotation(
                                                AnnotationSpec.builder(PutMapping.class)
                                                                .addMember("value", "$S", "/{id}")
                                                                .build())
                                .addParameter(
                                                ParameterSpec.builder(Long.class, "id")
                                                                .addAnnotation(PathVariable.class)
                                                                .build())
                                .addParameter(
                                                ParameterSpec.builder(entityType, variableName)
                                                                .addAnnotation(RequestBody.class)
                                                                .build())
                                .returns(responseEntityType)
                                .beginControlFlow("return repository.findById(id)\n    .map(existing ->")
                                .addStatement("// Update logic here")
                                .addStatement("return $T.ok(repository.save($L))", ResponseEntity.class, variableName)
                                .endControlFlow(")")
                                .addStatement(".orElse($T.notFound().build())", ResponseEntity.class)
                                .build();
        }

        private MethodSpec generateDeleteMethod(ParameterizedTypeName responseEntityType, String variableName) {
                return MethodSpec.methodBuilder("delete" + capitalize(variableName))
                                .addModifiers(Modifier.PUBLIC)
                                .addAnnotation(
                                                AnnotationSpec.builder(DeleteMapping.class)
                                                                .addMember("value", "$S", "/{id}")
                                                                .build())
                                .addParameter(
                                                ParameterSpec.builder(Long.class, "id")
                                                                .addAnnotation(PathVariable.class)
                                                                .build())
                                .returns(ParameterizedTypeName.get(ClassName.get(ResponseEntity.class),
                                                ClassName.get(Void.class)))
                                .addStatement("repository.deleteById(id)")
                                .addStatement("return $T.noContent().build()", ResponseEntity.class)
                                .build();
        }

        private String capitalize(String str) {
                if (str == null || str.isEmpty())
                        return str;
                return str.substring(0, 1).toUpperCase() + str.substring(1);
        }

        private String uncapitalize(String str) {
                if (str == null || str.isEmpty())
                        return str;
                return str.substring(0, 1).toLowerCase() + str.substring(1);
        }

        /**
         * Generate all controllers from analysis result
         */
        public Map<String, String> generateAllControllers(DiagramAnalysisResult analysisResult) {
                Map<String, String> generatedControllers = new LinkedHashMap<>();

                for (DiagramAnalysisResult.EntityMetadata entity : analysisResult.getEntities()) {
                        String controllerCode = generateController(entity, analysisResult.getBasePackage());
                        String fileName = entity.getName() + "Controller.java";
                        generatedControllers.put(fileName, controllerCode);
                }

                log.info("Generated {} controller classes", generatedControllers.size());
                return generatedControllers;
        }
}
