package com.archie.codegen.generator;

import com.archie.ai.model.DiagramAnalysisResult;
import com.squareup.javapoet.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import javax.lang.model.element.Modifier;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;

/**
 * Generates JPA entity classes using JavaPoet
 */
@Slf4j
@Component
public class EntityGenerator {

    /**
     * Generate JPA entity class code
     */
    public String generateEntity(DiagramAnalysisResult.EntityMetadata entity, String basePackage) {
        try {
            log.debug("Generating entity: {}", entity.getName());

            // Create entity class builder
            TypeSpec.Builder entityBuilder = TypeSpec.classBuilder(entity.getName())
                    .addModifiers(Modifier.PUBLIC)
                    .addAnnotation(Entity.class)
                    .addAnnotation(ClassName.get("lombok", "Data"))
                    .addAnnotation(ClassName.get("lombok", "Builder"))
                    .addAnnotation(ClassName.get("lombok", "NoArgsConstructor"))
                    .addAnnotation(ClassName.get("lombok", "AllArgsConstructor"));

            // Add @Table annotation if table name differs from entity name
            if (entity.getTableName() != null &&
                    !entity.getTableName().equalsIgnoreCase(entity.getName())) {
                entityBuilder.addAnnotation(
                        AnnotationSpec.builder(Table.class)
                                .addMember("name", "$S", entity.getTableName())
                                .build());
            }

            // Add fields
            for (DiagramAnalysisResult.AttributeMetadata attr : entity.getAttributes()) {
                FieldSpec field = generateField(attr);
                entityBuilder.addField(field);
            }

            // Generate Java file
            JavaFile javaFile = JavaFile.builder(basePackage + ".entity", entityBuilder.build())
                    .addFileComment("Auto-generated by Archie - Blueprint to Boot")
                    .addFileComment("Generated at: " + LocalDateTime.now())
                    .indent("    ")
                    .build();

            return javaFile.toString();

        } catch (Exception e) {
            log.error("Error generating entity {}: {}", entity.getName(), e.getMessage(), e);
            throw new RuntimeException("Failed to generate entity: " + e.getMessage(), e);
        }
    }

    /**
     * Generate entity field with JPA annotations
     */
    private FieldSpec generateField(DiagramAnalysisResult.AttributeMetadata attr) {
        FieldSpec.Builder fieldBuilder = FieldSpec.builder(
                getJavaType(attr.getType()),
                attr.getName(),
                Modifier.PRIVATE);

        // Add @Id for primary key
        if (attr.isPrimaryKey()) {
            fieldBuilder.addAnnotation(Id.class);
            fieldBuilder.addAnnotation(
                    AnnotationSpec.builder(GeneratedValue.class)
                            .addMember("strategy", "$T.IDENTITY", GenerationType.class)
                            .build());
        }

        // Add @Column annotation
        AnnotationSpec.Builder columnBuilder = AnnotationSpec.builder(Column.class)
                .addMember("nullable", "$L", attr.isNullable());

        if (attr.isUnique()) {
            columnBuilder.addMember("unique", "$L", true);
        }

        if (attr.getLength() != null && attr.getLength() > 0) {
            columnBuilder.addMember("length", "$L", attr.getLength());
        }

        fieldBuilder.addAnnotation(columnBuilder.build());

        return fieldBuilder.build();
    }

    /**
     * Map string type to Java class
     */
    private Class<?> getJavaType(String type) {
        return switch (type.toLowerCase()) {
            case "long", "bigint", "int64" -> Long.class;
            case "integer", "int", "int32" -> Integer.class;
            case "string", "varchar", "text", "char" -> String.class;
            case "boolean", "bool" -> Boolean.class;
            case "double", "float64" -> Double.class;
            case "float", "float32" -> Float.class;
            case "bigdecimal", "decimal", "numeric" -> BigDecimal.class;
            case "date", "timestamp", "datetime", "localdatetime" -> LocalDateTime.class;
            default -> String.class; // fallback
        };
    }

    /**
     * Generate all entities from analysis result
     */
    public Map<String, String> generateAllEntities(DiagramAnalysisResult analysisResult) {
        Map<String, String> generatedEntities = new LinkedHashMap<>();

        for (DiagramAnalysisResult.EntityMetadata entity : analysisResult.getEntities()) {
            String entityCode = generateEntity(entity, analysisResult.getBasePackage());
            String fileName = entity.getName() + ".java";
            generatedEntities.put(fileName, entityCode);
        }

        log.info("Generated {} entity classes", generatedEntities.size());
        return generatedEntities;
    }
}
