package com.archie.codegen.generator;

import com.archie.ai.model.DiagramAnalysisResult;
import com.squareup.javapoet.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import javax.lang.model.element.Modifier;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generates Spring Data JPA repository interfaces using JavaPoet
 */
@Slf4j
@Component
public class RepositoryGenerator {

    /**
     * Generate repository interface for an entity
     */
    public String generateRepository(DiagramAnalysisResult.EntityMetadata entity, String basePackage) {
        try {
            log.debug("Generating repository for: {}", entity.getName());

            String entityClassName = entity.getName();
            String repositoryName = entityClassName + "Repository";

            // Get ID type (assume Long for now)
            Class<?> idType = Long.class;

            // Create entity type reference
            ClassName entityType = ClassName.get(basePackage + ".entity", entityClassName);

            // Create JpaRepository parameterized type
            ParameterizedTypeName superInterface = ParameterizedTypeName.get(
                    ClassName.get(JpaRepository.class),
                    entityType,
                    TypeName.get(idType));

            // Build repository interface
            TypeSpec repository = TypeSpec.interfaceBuilder(repositoryName)
                    .addModifiers(Modifier.PUBLIC)
                    .addAnnotation(Repository.class)
                    .addSuperinterface(superInterface)
                    .addJavadoc("Spring Data JPA repository for $L entity\n", entityClassName)
                    .addJavadoc("Provides CRUD operations and custom query methods\n")
                    .build();

            // Generate Java file
            JavaFile javaFile = JavaFile.builder(basePackage + ".repository", repository)
                    .addFileComment("Auto-generated by Archie - Blueprint to Boot")
                    .indent("    ")
                    .build();

            return javaFile.toString();

        } catch (Exception e) {
            log.error("Error generating repository for {}: {}", entity.getName(), e.getMessage(), e);
            throw new RuntimeException("Failed to generate repository: " + e.getMessage(), e);
        }
    }

    /**
     * Generate all repositories from analysis result
     */
    public Map<String, String> generateAllRepositories(DiagramAnalysisResult analysisResult) {
        Map<String, String> generatedRepositories = new LinkedHashMap<>();

        for (DiagramAnalysisResult.EntityMetadata entity : analysisResult.getEntities()) {
            String repositoryCode = generateRepository(entity, analysisResult.getBasePackage());
            String fileName = entity.getName() + "Repository.java";
            generatedRepositories.put(fileName, repositoryCode);
        }

        log.info("Generated {} repository interfaces", generatedRepositories.size());
        return generatedRepositories;
    }
}
